import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const RiskReportPage = () => {
  const navigate = useNavigate();
  const [predictions, setPredictions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [filter, setFilter] = useState('all');
  const [toast, setToast] = useState(null);

  // Toast notification function
  const showToast = (message, type = 'success') => {
    setToast({ message, type });
    setTimeout(() => setToast(null), 4000);
  };

  useEffect(() => {
    fetchRecentPredictions();
  }, []);

  const fetchRecentPredictions = async () => {
    setLoading(true);
    setError(null);

    try {
      const response = await fetch('http://localhost:5000/api/stats');
      
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      
      const data = await response.json();
      setPredictions(data.recent_predictions || []);
      setLoading(false);
    } catch (err) {
      console.error('Error fetching predictions:', err);
      setError(err.message);
      setLoading(false);
    }
  };

  const exportToPDF = async () => {
    try {
      // Fetch all predictions and stats
      const [predictionsRes, statsRes] = await Promise.all([
        fetch('http://localhost:5000/api/predictions?limit=1000'),
        fetch('http://localhost:5000/api/stats')
      ]);
      
      if (!predictionsRes.ok || !statsRes.ok) {
        throw new Error('Failed to fetch data');
      }
      
      const predictionsData = await predictionsRes.json();
      const statsData = await statsRes.json();
      const allPredictions = predictionsData.predictions || [];

      if (allPredictions.length === 0) {
        showToast('No predictions to export', 'error');
        return;
      }

      // Create PDF
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      let yPos = 20;

      // Helper function to add new page if needed
      const checkPageBreak = (requiredSpace = 20) => {
        if (yPos + requiredSpace > pageHeight - 20) {
          doc.addPage();
          yPos = 20;
          return true;
        }
        return false;
      };

      // Title Page
      doc.setFillColor(139, 92, 246);
      doc.rect(0, 0, pageWidth, 40, 'F');
      
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(24);
      doc.setFont(undefined, 'bold');
      doc.text('Terra Alert', pageWidth / 2, 20, { align: 'center' });
      
      doc.setFontSize(16);
      doc.setFont(undefined, 'normal');
      doc.text('Landslide Risk Prediction Report', pageWidth / 2, 32, { align: 'center' });

      yPos = 50;
      doc.setTextColor(0, 0, 0);

      // Report Information
      doc.setFontSize(10);
      doc.setFont(undefined, 'normal');
      doc.text(`Generated: ${new Date().toLocaleString()}`, 14, yPos);
      yPos += 6;
      doc.text(`Total Predictions: ${allPredictions.length}`, 14, yPos);
      yPos += 6;
      doc.text(`Report Period: All Time`, 14, yPos);
      yPos += 15;

      // Executive Summary
      doc.setFontSize(14);
      doc.setFont(undefined, 'bold');
      doc.setTextColor(139, 92, 246);
      doc.text('Executive Summary', 14, yPos);
      yPos += 8;

      doc.setFontSize(10);
      doc.setFont(undefined, 'normal');
      doc.setTextColor(0, 0, 0);
      
      const summaryText = [
        'This report provides a comprehensive analysis of landslide risk predictions generated by the Terra Alert system.',
        'The predictions are based on machine learning models that analyze multiple environmental factors including terrain,',
        'rainfall patterns, soil conditions, and vegetation indices. Each prediction is classified into risk levels ranging',
        'from LOW to CRITICAL, enabling authorities to take appropriate preventive measures.'
      ];
      
      summaryText.forEach(line => {
        doc.text(line, 14, yPos);
        yPos += 5;
      });
      yPos += 10;

      // Statistics Overview
      checkPageBreak(60);
      doc.setFontSize(14);
      doc.setFont(undefined, 'bold');
      doc.setTextColor(139, 92, 246);
      doc.text('Risk Distribution', 14, yPos);
      yPos += 10;

      // Stats boxes
      const stats = [
        { label: 'Critical', value: statsData.critical_count || 0, color: [239, 68, 68] },
        { label: 'High', value: statsData.high_count || 0, color: [249, 115, 22] },
        { label: 'Moderate', value: statsData.moderate_count || 0, color: [234, 179, 8] },
        { label: 'Low', value: statsData.low_count || 0, color: [16, 185, 129] }
      ];

      const boxWidth = 40;
      const boxHeight = 25;
      const spacing = 10;
      let xPos = 14;

      stats.forEach(stat => {
        doc.setFillColor(...stat.color);
        doc.roundedRect(xPos, yPos, boxWidth, boxHeight, 3, 3, 'F');
        
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(18);
        doc.setFont(undefined, 'bold');
        doc.text(stat.value.toString(), xPos + boxWidth / 2, yPos + 12, { align: 'center' });
        
        doc.setFontSize(9);
        doc.setFont(undefined, 'normal');
        doc.text(stat.label, xPos + boxWidth / 2, yPos + 20, { align: 'center' });
        
        xPos += boxWidth + spacing;
      });

      yPos += boxHeight + 15;
      doc.setTextColor(0, 0, 0);

      // Average Risk Score
      doc.setFontSize(10);
      doc.text(`Average Risk Score: ${statsData.avg_risk_score?.toFixed(1) || 'N/A'} / 100`, 14, yPos);
      yPos += 6;
      doc.text(`Highest Risk Location: ${statsData.highest_risk_location || 'N/A'}`, 14, yPos);
      yPos += 15;

      // Risk Level Explanation
      checkPageBreak(80);
      doc.setFontSize(14);
      doc.setFont(undefined, 'bold');
      doc.setTextColor(139, 92, 246);
      doc.text('Risk Level Classification', 14, yPos);
      yPos += 10;

      const riskLevels = [
        { level: 'CRITICAL (80-100)', color: [239, 68, 68], desc: 'Immediate action required. High probability of landslide occurrence.' },
        { level: 'HIGH (60-79)', color: [249, 115, 22], desc: 'Significant risk. Close monitoring and preventive measures recommended.' },
        { level: 'MODERATE (40-59)', color: [234, 179, 8], desc: 'Moderate risk. Regular monitoring advised.' },
        { level: 'LOW (0-39)', color: [16, 185, 129], desc: 'Low risk. Standard monitoring protocols sufficient.' }
      ];

      doc.setFontSize(9);
      riskLevels.forEach(risk => {
        doc.setFillColor(...risk.color);
        doc.circle(17, yPos - 1, 2, 'F');
        
        doc.setFont(undefined, 'bold');
        doc.setTextColor(0, 0, 0);
        doc.text(risk.level, 22, yPos);
        
        doc.setFont(undefined, 'normal');
        doc.setTextColor(80, 80, 80);
        const lines = doc.splitTextToSize(risk.desc, pageWidth - 30);
        doc.text(lines, 22, yPos + 4);
        
        yPos += 12;
      });

      yPos += 10;

      // Detailed Predictions Table
      doc.addPage();
      yPos = 20;
      
      doc.setFontSize(14);
      doc.setFont(undefined, 'bold');
      doc.setTextColor(139, 92, 246);
      doc.text('Detailed Predictions', 14, yPos);
      yPos += 10;

      // Prepare table data
      const tableData = allPredictions.map((pred, index) => [
        (index + 1).toString(),
        pred.location || 'Unknown',
        `${pred.lat?.toFixed(4) || 'N/A'}, ${pred.lon?.toFixed(4) || 'N/A'}`,
        pred.score?.toString() || '0',
        pred.level || 'UNKNOWN',
        pred.elevation?.toString() || 'N/A',
        pred.slope?.toString() || 'N/A',
        pred.rainfall_30d?.toString() || 'N/A',
        new Date(pred.created_at).toLocaleDateString() || 'N/A'
      ]);

      autoTable(doc, {
        startY: yPos,
        head: [['#', 'Location', 'Coordinates', 'Score', 'Level', 'Elev.(m)', 'Slope(°)', 'Rain(mm)', 'Date']],
        body: tableData,
        theme: 'grid',
        headStyles: {
          fillColor: [139, 92, 246],
          textColor: [255, 255, 255],
          fontSize: 8,
          fontStyle: 'bold'
        },
        bodyStyles: {
          fontSize: 7,
          textColor: [0, 0, 0]
        },
        alternateRowStyles: {
          fillColor: [245, 245, 245]
        },
        columnStyles: {
          0: { cellWidth: 10 },
          1: { cellWidth: 35 },
          2: { cellWidth: 35 },
          3: { cellWidth: 15 },
          4: { cellWidth: 20 },
          5: { cellWidth: 18 },
          6: { cellWidth: 18 },
          7: { cellWidth: 18 },
          8: { cellWidth: 22 }
        },
        didParseCell: function(data) {
          // Color code risk levels
          if (data.column.index === 4 && data.section === 'body') {
            const level = data.cell.raw;
            if (level === 'CRITICAL') {
              data.cell.styles.fillColor = [239, 68, 68];
              data.cell.styles.textColor = [255, 255, 255];
            } else if (level === 'HIGH') {
              data.cell.styles.fillColor = [249, 115, 22];
              data.cell.styles.textColor = [255, 255, 255];
            } else if (level === 'MODERATE') {
              data.cell.styles.fillColor = [234, 179, 8];
              data.cell.styles.textColor = [255, 255, 255];
            } else if (level === 'LOW') {
              data.cell.styles.fillColor = [16, 185, 129];
              data.cell.styles.textColor = [255, 255, 255];
            }
          }
        }
      });

      // Footer on last page
      const totalPages = doc.internal.pages.length - 1;
      for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(128, 128, 128);
        doc.text(
          `Page ${i} of ${totalPages}`,
          pageWidth / 2,
          pageHeight - 10,
          { align: 'center' }
        );
        doc.text(
          'Terra Alert - Landslide Risk Prediction System',
          14,
          pageHeight - 10
        );
      }

      // Methodology Page
      doc.addPage();
      yPos = 20;
      
      doc.setFontSize(14);
      doc.setFont(undefined, 'bold');
      doc.setTextColor(139, 92, 246);
      doc.text('Methodology', 14, yPos);
      yPos += 10;

      doc.setFontSize(10);
      doc.setFont(undefined, 'normal');
      doc.setTextColor(0, 0, 0);

      const methodology = [
        'Data Collection:',
        '• Satellite imagery from Google Earth Engine',
        '• Terrain data (elevation, slope, aspect)',
        '• Rainfall patterns (3, 7, 14, and 30-day periods)',
        '• Vegetation indices (NDVI, NDWI)',
        '• Soil type classification',
        '',
        'Machine Learning Model:',
        '• Algorithm: XGBoost (Extreme Gradient Boosting)',
        '• Model Accuracy: 97%',
        '• Features: 20 environmental parameters',
        '• Training Data: Historical landslide events',
        '',
        'Risk Assessment:',
        '• Real-time analysis of environmental conditions',
        '• Multi-factor risk scoring (0-100 scale)',
        '• Automated classification into risk levels',
        '• Confidence scoring for each prediction'
      ];

      methodology.forEach(line => {
        if (line === '') {
          yPos += 5;
        } else {
          doc.text(line, 14, yPos);
          yPos += 6;
        }
      });

      // Save PDF
      const filename = `Terra-Alert-Risk-Report-${new Date().toISOString().split('T')[0]}.pdf`;
      doc.save(filename);

      showToast(`Successfully generated PDF report with ${allPredictions.length} predictions`, 'success');
    } catch (err) {
      console.error('Error generating PDF:', err);
      showToast('Failed to generate PDF report: ' + err.message, 'error');
    }
  };

  const exportToCSV = async () => {
    try {
      // Fetch all predictions from the database
      const response = await fetch('http://localhost:5000/api/predictions?limit=1000');
      
      if (!response.ok) {
        throw new Error('Failed to fetch predictions');
      }
      
      const data = await response.json();
      const allPredictions = data.predictions || [];

      if (allPredictions.length === 0) {
        showToast('No predictions to export', 'error');
        return;
      }

      // Create CSV header
      const headers = [
        'ID',
        'Date & Time',
        'Location Name',
        'Latitude',
        'Longitude',
        'Risk Score',
        'Risk Level',
        'Confidence (%)',
        'Elevation (m)',
        'Slope (°)',
        'Aspect (°)',
        'NDVI',
        'NDWI',
        'Soil Type',
        'Rainfall 3d (mm)',
        'Rainfall 7d (mm)',
        'Rainfall 14d (mm)',
        'Rainfall 30d (mm)',
        'Top Risk Factor'
      ];

      // Create CSV rows
      const rows = allPredictions.map((pred, index) => {
        return [
          index + 1,
          pred.created_at || 'N/A',
          pred.location || 'Unknown',
          pred.lat?.toFixed(6) || 'N/A',
          pred.lon?.toFixed(6) || 'N/A',
          pred.score || 0,
          pred.level || 'UNKNOWN',
          pred.confidence || 'N/A',
          pred.elevation || 'N/A',
          pred.slope || 'N/A',
          pred.aspect || 'N/A',
          pred.ndvi || 'N/A',
          pred.ndwi || 'N/A',
          pred.soil_type || 'N/A',
          pred.rainfall_3d || 'N/A',
          pred.rainfall_7d || 'N/A',
          pred.rainfall_14d || 'N/A',
          pred.rainfall_30d || 'N/A',
          pred.top_factor || 'N/A'
        ];
      });

      // Combine headers and rows
      const csvContent = [
        // Title row
        ['Terra Alert - Landslide Risk Prediction Report'],
        ['Generated on: ' + new Date().toLocaleString()],
        ['Total Predictions: ' + allPredictions.length],
        [], // Empty row
        // Headers
        headers,
        // Data rows
        ...rows
      ].map(row => row.join(',')).join('\n');

      // Create blob and download
      const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
      const link = document.createElement('a');
      const url = URL.createObjectURL(blob);
      
      link.setAttribute('href', url);
      link.setAttribute('download', `terra-alert-risk-report-${new Date().toISOString().split('T')[0]}.csv`);
      link.style.visibility = 'hidden';
      
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);

      showToast(`Successfully exported ${allPredictions.length} predictions to CSV`, 'success');
    } catch (err) {
      console.error('Error exporting CSV:', err);
      showToast('Failed to export report: ' + err.message, 'error');
    }
  };

  const getRiskColor = (score) => {
    if (score >= 80) return 'text-red-400';
    if (score >= 60) return 'text-orange-400';
    if (score >= 40) return 'text-yellow-400';
    return 'text-emerald-400';
  };

  const getLevelBadge = (level) => {
    const badges = {
      CRITICAL: 'bg-red-500 text-white',
      HIGH: 'bg-orange-500 text-white',
      MODERATE: 'bg-yellow-500 text-white',
      LOW: 'bg-emerald-500 text-white'
    };
    return badges[level] || badges.LOW;
  };

  const getLevelDot = (level) => {
    const dots = {
      CRITICAL: 'bg-red-500',
      HIGH: 'bg-orange-500',
      MODERATE: 'bg-yellow-500',
      LOW: 'bg-emerald-500'
    };
    return dots[level] || dots.LOW;
  };

  const filteredPredictions = predictions.filter(pred => {
    if (filter === 'all') return true;
    return pred.level.toLowerCase() === filter;
  });

  const stats = {
    total: predictions.length,
    critical: predictions.filter(p => p.level === 'CRITICAL').length,
    high: predictions.filter(p => p.level === 'HIGH').length,
    moderate: predictions.filter(p => p.level === 'MODERATE').length,
    low: predictions.filter(p => p.level === 'LOW').length,
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center">
          <div className="w-16 h-16 border-4 border-violet-400/30 border-t-violet-400 rounded-full animate-spin mx-auto mb-4" />
          <p className="text-white/60">Loading predictions...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen flex items-center justify-center p-8">
        <div className="bg-red-500/10 border border-red-500/30 rounded-lg p-6 max-w-md">
          <h3 className="text-red-400 font-semibold mb-2">Error Loading Report</h3>
          <p className="text-white/60 text-sm mb-4">{error}</p>
          <button
            onClick={fetchRecentPredictions}
            className="px-4 py-2 bg-violet-600 hover:bg-violet-700 text-white rounded-lg transition-colors"
          >
            Retry
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen p-8">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="flex items-center justify-between mb-8">
          <div>
            <h1 className="text-3xl font-bold text-white mb-1">Risk Report</h1>
            <p className="text-white/60">Recent landslide risk predictions</p>
          </div>
          <button
            onClick={fetchRecentPredictions}
            className="px-4 py-2 bg-white/10 hover:bg-white/15 text-white rounded-lg transition-colors border border-white/20 flex items-center gap-2"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
            </svg>
            Refresh
          </button>
        </div>

        {/* Filter Stats */}
        <div className="grid grid-cols-5 gap-3 mb-6">
          {[
            { key: 'all', label: 'Total', value: stats.total, color: 'violet' },
            { key: 'critical', label: 'Critical', value: stats.critical, color: 'red' },
            { key: 'high', label: 'High', value: stats.high, color: 'orange' },
            { key: 'moderate', label: 'Moderate', value: stats.moderate, color: 'yellow' },
            { key: 'low', label: 'Low', value: stats.low, color: 'emerald' }
          ].map(stat => (
            <button
              key={stat.key}
              onClick={() => setFilter(stat.key)}
              className={`p-3 rounded-lg border transition-all ${
                filter === stat.key 
                  ? `bg-${stat.color}-500/20 border-${stat.color}-500/50` 
                  : 'bg-white/5 border-white/10 hover:bg-white/10'
              }`}
            >
              <div className={`text-2xl font-bold mb-1 ${filter === stat.key ? `text-${stat.color}-400` : 'text-white'}`}>
                {stat.value}
              </div>
              <div className="text-xs text-white/60">{stat.label}</div>
            </button>
          ))}
        </div>

        {/* Predictions Table */}
        {filteredPredictions.length === 0 ? (
          <div className="bg-white/5 border border-white/10 rounded-lg p-12 text-center">
            <div className="text-5xl mb-4">📊</div>
            <h3 className="text-xl font-semibold text-white mb-2">No Predictions Found</h3>
            <p className="text-white/60 mb-4">
              {filter === 'all' 
                ? 'Start making predictions to see them here' 
                : `No ${filter} risk predictions found`}
            </p>
            {filter !== 'all' && (
              <button
                onClick={() => setFilter('all')}
                className="px-6 py-2 bg-violet-600 hover:bg-violet-700 text-white rounded-lg transition-colors"
              >
                Show All
              </button>
            )}
          </div>
        ) : (
          <div className="space-y-2">
            {filteredPredictions.map((pred, index) => (
              <div
                key={pred.id}
                className="bg-white/5 border border-white/10 rounded-lg p-4 hover:bg-white/8 hover:border-white/20 transition-all"
              >
                <div className="flex items-center gap-4">
                  {/* Index */}
                  <div className="w-8 h-8 rounded-full bg-white/10 flex items-center justify-center text-sm font-semibold text-white/80">
                    {index + 1}
                  </div>

                  {/* Status Dot */}
                  <div className={`w-3 h-3 rounded-full ${getLevelDot(pred.level)}`} />

                  {/* Location */}
                  <div className="flex-1 min-w-0">
                    <div className="font-medium text-white truncate">{pred.location}</div>
                    <div className="text-xs text-white/50">{pred.lat.toFixed(4)}°, {pred.lon.toFixed(4)}°</div>
                  </div>

                  {/* Risk Score */}
                  <div className="text-center">
                    <div className={`text-3xl font-bold ${getRiskColor(pred.score)}`}>
                      {pred.score}
                    </div>
                    <div className="text-xs text-white/50">Risk Score</div>
                  </div>

                  {/* Level Badge */}
                  <div>
                    <span className={`px-4 py-1.5 rounded-md text-sm font-semibold ${getLevelBadge(pred.level)}`}>
                      {pred.level}
                    </span>
                  </div>

                  {/* Features */}
                  <div className="grid grid-cols-4 gap-4 text-xs">
                    <div className="text-center">
                      <div className="text-white/50">Elevation</div>
                      <div className="text-white font-medium">{pred.elevation}m</div>
                    </div>
                    <div className="text-center">
                      <div className="text-white/50">Slope</div>
                      <div className="text-white font-medium">{pred.slope}°</div>
                    </div>
                    <div className="text-center">
                      <div className="text-white/50">Rain</div>
                      <div className="text-white font-medium">{pred.rainfall_30d}mm</div>
                    </div>
                    <div className="text-center">
                      <div className="text-white/50">Conf.</div>
                      <div className="text-white font-medium">{pred.confidence}%</div>
                    </div>
                  </div>

                  {/* Action */}
                  <button
                    onClick={() => navigate(`/map?lat=${pred.lat}&lon=${pred.lon}`)}
                    className="p-2 rounded-lg bg-violet-600 hover:bg-violet-700 text-white transition-colors"
                    title="View on Map"
                  >
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
                    </svg>
                  </button>
                </div>

                {/* Timestamp */}
                <div className="mt-2 ml-12 text-xs text-white/40 flex items-center gap-1">
                  <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                  {pred.ts}
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Export Buttons */}
        {filteredPredictions.length > 0 && (
          <div className="mt-6 flex justify-center gap-4">
            <button 
              onClick={exportToPDF}
              className="px-6 py-3 bg-violet-600 hover:bg-violet-700 text-white rounded-lg transition-colors flex items-center gap-2"
            >
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
              </svg>
              Export PDF Report
            </button>
            <button 
              onClick={exportToCSV}
              className="px-6 py-3 bg-white/10 hover:bg-white/15 text-white rounded-lg transition-colors border border-white/20 flex items-center gap-2"
            >
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              Export CSV
            </button>
          </div>
        )}
      </div>

      {/* Toast Notification */}
      {toast && (
        <div className="fixed bottom-8 right-8 z-50 animate-slide-up">
          <div className={`px-6 py-4 rounded-lg shadow-lg border flex items-center gap-3 ${
            toast.type === 'success' 
              ? 'bg-emerald-500/90 border-emerald-400 text-white' 
              : 'bg-red-500/90 border-red-400 text-white'
          }`}>
            {toast.type === 'success' ? (
              <svg className="w-6 h-6 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            ) : (
              <svg className="w-6 h-6 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            )}
            <span className="font-medium">{toast.message}</span>
            <button 
              onClick={() => setToast(null)}
              className="ml-2 hover:opacity-80"
            >
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default RiskReportPage;
